# Fase 1: Construcción de la aplicación Angular
FROM node:20 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración de npm
COPY package*.json ./

# Instalar las dependencias de Angular
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

# Construir la aplicación Angular Universal (SSR)
RUN npm run build:ssr  # Este comando construye tanto el cliente como el servidor

# Fase 2: Servir la aplicación con Nginx y Node.js

# Usar una imagen oficial de Node.js para el SSR
FROM node:20 AS runtime

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos generados por el build de Angular
COPY --from=build /app/dist/mediashop-frontend/browser /usr/share/nginx/html/
COPY --from=build /app/dist/mediashop-frontend/server /app/server/

# Instalar Nginx para servir los archivos estáticos
RUN apt-get update && apt-get install -y nginx

# Copiar la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto para Nginx y el servidor Node.js
EXPOSE 80
EXPOSE 4000

# Ejecutar el servidor de Node.js para SSR y Nginx para los archivos estáticos
CMD ["sh", "-c", "node /app/server/main.js & nginx -g 'daemon off;'"]
