# Fase 1: Construcción de la aplicación Angular
FROM node:20 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración de npm
COPY ./package*.json ./

# Instalar las dependencias de Angular
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY ./ ./

# Construir la aplicación Angular Universal (SSR)
RUN npm run prod  # Este comando construye tanto el cliente como el servidor

# Usar una imagen oficial de Node.js para el SSR
FROM nginx:alpine

# Instalar Node.js y otras dependencias necesarias para el SSR
RUN apk update && apk add --no-cache \
  nodejs \
  npm \
  bash \
  && rm -rf /var/cache/apk/*

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos generados por el build de Angular
COPY --from=build /app/dist/mediashop-frontend/browser /usr/share/nginx/html/
COPY --from=build /app/dist/mediashop-frontend/server /app/server/

# Instalar Nginx para servir los archivos estáticos
RUN apk update && apk add nginx

# Copiar la configuración personalizada de Nginx
COPY ./nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto para Nginx y el servidor Node.js
EXPOSE 80
EXPOSE 4000

# Ejecutar el servidor Node.js para SSR y Nginx para los archivos estáticos
CMD ["sh", "-c", "node /app/server/server.mjs & nginx -g 'daemon off;'"]
