# Usar una imagen oficial de Nginx para servir los archivos estáticos
FROM nginx:alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos generados por el build de Angular (ya compilados) a la carpeta pública de Nginx
COPY ./dist/demo1 /usr/share/nginx/html/

# Instalar Node.js (si fuera necesario para otros usos)
RUN apk update && apk add --no-cache \
  nodejs \
  npm \
  bash \
  && rm -rf /var/cache/apk/*

# Instalar Nginx para servir los archivos estáticos
RUN apk update && apk add nginx

# Copiar la configuración personalizada de Nginx
COPY ./nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto para Nginx
EXPOSE 80

# Ejecutar Nginx para los archivos estáticos
CMD ["nginx", "-g", "daemon off;"]
